CREATE TABLE Symbol (
    Symbol      VARCHAR(10) PRIMARY KEY,
    LastUpdated DATETIME
)

CREATE TABLE DataPoint (
    Symbol              VARCHAR(10) REFERENCES Symbol(Symbol),
    Date                DATE NOT NULL,
    [Open]              FLOAT NOT NULL,
    High                FLOAT NOT NULL,
    Low                 FLOAT NOT NULL,
    [Close]             FLOAT NOT NULL,
    AdjustedClose       FLOAT NOT NULL,
    Volume              BIGINT NOT NULL,
    DividendAmount      FLOAT NOT NULL,
    SplitCoefficient    FLOAT NOT NULL,
    PRIMARY KEY (Symbol, Date)
)

CREATE TABLE CompanyOverview (
    Symbol                      VARCHAR(10) PRIMARY KEY REFERENCES Symbol(Symbol),
    AssetType                   VARCHAR(255) NOT NULL,
    Name                        VARCHAR(255) NOT NULL,
    Description                 VARCHAR(5000) NOT NULL,
    CIK                         VARCHAR(255) NOT NULL,
    Exchange                    VARCHAR(255) NOT NULL,
    Currency                    VARCHAR(255) NOT NULL,
    Country                     VARCHAR(255) NOT NULL,
    Sector                      VARCHAR(255) NOT NULL,
    Industry                    VARCHAR(255) NOT NULL,
    Address                     VARCHAR(255) NOT NULL,
    FiscalYearEnd               VARCHAR(255) NOT NULL,
    LatestQuarter               DATE NOT NULL,
    MarketCapitalization        BIGINT NOT NULL,
    EBITDA                      BIGINT,
    PERatio                     FLOAT,
    PEGRatio                    FLOAT,
    BookValue                   FLOAT,
    DividendPerShare            FLOAT,
    DividendYield               FLOAT,
    EPS                         FLOAT,
    RevenuePerShareTTM          FLOAT,
    ProfitMargin                FLOAT,
    OperatingMarginTTM          FLOAT,
    ReturnOnAssetsTTM           FLOAT,
    ReturnOnEquityTTM           FLOAT,
    RevenueTTM                  BIGINT,
    GrossProfitTTM              BIGINT,
    DilutedEPSTTM               FLOAT,
    QuarterlyEarningsGrowthYOY  FLOAT,
    QuarterlyRevenueGrowthYOY   FLOAT,
    AnalystTargetPrice          FLOAT,
    TrailingPE                  FLOAT,
    ForwardPE                   FLOAT,
    PriceToSalesRatioTTM        FLOAT,
    PriceToBookRatio            FLOAT,
    EVToRevenue                 FLOAT,
    EVToEBITDA                  FLOAT,
    Beta                        FLOAT,
    [52WeekHigh]                FLOAT,
    [52WeekLow]                 FLOAT,
    [50DayMovingAverage]        FLOAT,
    [200DayMovingAverage]       FLOAT,
    SharesOutstanding           BIGINT,
    DividendDate                DATE,
    ExDividendDate              DATE,
)
